#!/usr/bin/env perl
use strict;
use warnings;
use open qw< :std :encoding(UTF-8) >;
use Clipboard;

BEGIN {
    if ($Clipboard::driver->isa('Clipboard::Xclip')) {
        no warnings 'redefine';
        *Clipboard::Xclip::all_selections = sub {
            qw(clipboard primary buffer secondary);
        };
    }
}

my $text = do { undef $/; <>; };
Clipboard->copy($text);

my $lines = $text =~ y/\n/\n/;
printf "Copied %d line%s\n", $lines, $lines != 1 ? "s" : "";
