#!/bin/bash
set -e -o pipefail

os=$(uname -s)
case $os in
    Linux)
        copy="xclip -i -selection clipboard"
        ;;
    Darwin)
        copy="pbcopy -Prefer txt"
        ;;
    *)
        echo "I don’t know how to get cozy with the clipboard on $os…" >&2
        exit 1
        ;;
esac

function count_lines() {
    lines=$(wc -l | perl -pe 's/\s+//g')
    if [[ $lines -lt 2 ]]; then
        echo "Copied 1 line"
    else
        echo "Copied $lines lines"
    fi
}

# Copy contents of named files or stdin
cat "$@" | tee >($copy >/dev/null) | count_lines
